### ISSUE TITLE
i == 0 일 때도 수행되는 로직인지 확인 

### ISSUE THREAD

**Issue by kmu-yoonsh** [CMS0503/CodeOnBoard#10]
https://github.com/CMS0503/CodeOnBoard/blob/325978571ef1dcc11458b726d493f707c4fb1540/CORE/gamemanager.py#L190

```
if i == 0 
if i == 1
else 

```
이므로 else가 i == 0 일 때도 적용되는 로직인지 확인해주세요.

**Comment by Navifra-Chris** [comment]
i가 0일 때 중복되는 것을 확인하여 합쳤습니다.
