### ISSUE TITLE
pass를 넣은 이유 

### ISSUE THREAD

**Issue by kmu-yoonsh** [CMS0503/CodeOnBoard#11]
https://github.com/CMS0503/CodeOnBoard/blob/325978571ef1dcc11458b726d493f707c4fb1540/CORE/gamemanager.py#L324

not in 으로 처리하면 되는데 

in 으로 검사하고 pass 하고 있는 이유가 있을까요?

**Comment by Navifra-Chris** [comment]
사용하지 않는 함수라 삭제했습니다.
