### ISSUE TITLE
중복 코드 처리 

### ISSUE THREAD

**Issue by kmu-yoonsh** [CMS0503/CodeOnBoard#12]
https://github.com/CMS0503/CodeOnBoard/blob/325978571ef1dcc11458b726d493f707c4fb1540/CORE/rule/ending_rule.py#L70

https://github.com/CMS0503/CodeOnBoard/blob/325978571ef1dcc11458b726d493f707c4fb1540/CORE/rule/ending_rule.py#L85

**Comment by Navifra-Chris** [comment]
사용하지 않는 함수라 삭제했습니다.
