### ISSUE TITLE
boolean형에 대한 검사시 

### ISSUE THREAD

**Issue by kmu-yoonsh** [CMS0503/CodeOnBoard#5]
https://github.com/CMS0503/CodeOnBoard/blob/325978571ef1dcc11458b726d493f707c4fb1540/CORE/gamemanager.py#L117

```
if is_ending: 
if not is_ending:

```
이 더 간단명료합니다. 
다른 사람들의 코드를 많이 읽어 봤으면 하는 바램입니다.

**Comment by Navifra-Chris** [comment]
해당 코드 모두 변경했습니다.
