### ISSUE TITLE
Challenger, opposite 등의 값 구분 형식 변경

### ISSUE THREAD

**Issue by kmu-yoonsh** [CMS0503/CodeOnBoard#8]
https://github.com/CMS0503/CodeOnBoard/blob/325978571ef1dcc11458b726d493f707c4fb1540/CORE/gamemanager.py#L67

문자열로 사용하는 것은 오타에 의한 버그를 발생시키기 때문에 
권장하지 않습니다. 

파이썬에서 이러한 값들을 구분하는 방법을 찾아보고 적용하세요.

**Comment by Navifra-Chris** [comment]
challenger -> 1
opposite -> -1

숫자로 변경했습니다.
