### ISSUE TITLE
삼항 연산자

### ISSUE THREAD

**Issue by kmu-yoonsh** [CMS0503/CodeOnBoard#9]
https://github.com/CMS0503/CodeOnBoard/blob/325978571ef1dcc11458b726d493f707c4fb1540/CORE/gamemanager.py#L122

134라인처럼 삼항 연산자

**Comment by kmu-yoonsh** [comment]
이 구문이 많은 곳에 있는데 함수로 만들면 어떨까요 ?

**Comment by Navifra-Chris** [comment]
중복되는 코드 함수처리 했습니다.
